# Numpy

In [1]:
'''
NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".
'''


'\nNumPy is a Python library.\n\nNumPy is used for working with arrays.\n\nNumPy is short for "Numerical Python".\n'

### Create a Numpy Array

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
# version of numpy
print(np.__version__)

1.21.5


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


### Dimentions of arrray

In [8]:
# 0-D Array

arr = np.array(43)
print(arr)

43


In [9]:
# 1-D Array

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [10]:
# 2-D Array

arr = np.array([[1, 2, 3], [2, 4, 6]])
print(arr)

[[1 2 3]
 [2 4 6]]


In [11]:
# 3-D Array

arr = np.array([[[1, 2, 3], [2, 4, 6]], [[5, 10, 15], [10, 20, 30]]])
print(arr)

[[[ 1  2  3]
  [ 2  4  6]]

 [[ 5 10 15]
  [10 20 30]]]


In [13]:
# Checkling the dimentions 

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Numpy Array Indexing

In [14]:
# Index starts from 0 
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[0])
print(arr[4])

1
5


In [15]:
arr = np.array([[1, 2, 3], [6, 9, 12]])
print(arr[1, 2])

12


In [16]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[10, 20, 30, 40], [50, 100, 150, 200]]])
print(arr[1, 0, 2])

30


### Numpy Array Slicing

In [18]:
'''
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1
'''

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
#Note: The result includes the start index, but excludes the end index.

[2 3 4 5]


In [19]:
print(arr[4:])

[5 6 7]


In [20]:
print(arr[:4])

[1 2 3 4]


In [21]:
print(arr[-3:-1])

[5 6]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [23]:
print(arr[::2])

[1 3 5 7]


In [24]:
# Slicing 2-D array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [25]:
print(arr[0:2, 2])

[3 8]


In [26]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### Numpy Data Types 

In [28]:
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1.1, 2.1, 3.1])
arr3 = np.array(['apple', 'banana', 'cherry'])

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
float64
<U6


### Numpy Copy vs View

In [30]:
'''
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.
'''

# Copy
arr = np.array([1, 2, 3, 4, 5, 6, 7])

copy_arr = arr.copy()

arr[0] = 43

print("Original Array", arr)
print("Copied Array", copy_arr)

Original Array [43  2  3  4  5  6  7]
Copied Array [1 2 3 4 5 6 7]


In [32]:
# View

arr = np.array([1, 2, 3, 4, 5, 6, 7])

view_arr = arr.view()

arr[0] = 43

print("Original Array", arr)
print("Viewed Array", view_arr)

Original Array [43  2  3  4  5  6  7]
Viewed Array [43  2  3  4  5  6  7]


### Numpy Array Shape

In [35]:
# Get the Shape of an Array

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10]])
arr3 = np.array([[[1, 3, 5, 7], [3, 5, 7, 9]], [[2, 4, 6, 8], [5, 10, 15, 20]]])

print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 5)
(2, 2, 4)


### Array Reshape

In [39]:
# Reshape From 1-D to 2-D

arr = np.array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])
new_arr = arr.reshape(5, 2)
print("Original Array", arr)
print("After Reshape\n", new_arr)

Original Array [1 2 3 4 5 1 2 3 4 5]
After Reshape
 [[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]


In [41]:
# Reshape From 1-D to 3-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### NumPy Array Iterating

In [42]:
'''
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.
'''

# Iterating 1-D Array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for a in arr:
    print(a)

1
2
3
4
5
6
7
8
9
10
11
12


In [43]:
# Iterating 2-D array

arr = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10]])

# If we iterate on a n-D array it will go through n-1th dimension one by one.
for a in arr:
    print(a)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [44]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.

for a in arr:
    for x in a:
        print(x)

1
2
3
4
5
2
4
6
8
10


In [45]:
# Iterating 3-D Arrays

# In a 3-D array it will go through all the 2-D arrays.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for a in arr:
    print(a)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [46]:
for a in arr:
    for x in a:
        print(x)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [47]:
for a in arr:
    for x in a:
        for y in x:
            print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [49]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


### Numpy Array Join

In [51]:
# Joining means putting contents of two or more arrays in a single array.


#join 2 1-D array

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [52]:
# Join 2 2-D array

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [53]:
# Joining using stack()

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [54]:
# Stacking along rows
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [55]:
# Stacking along columns

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [56]:
# Stacking along height (depth)

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Numpy Array Splict

In [57]:
'''
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
'''


arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [59]:
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [60]:
# Splict 2-D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [61]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Numpy Array Search

In [64]:
'''
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.
'''

print("Find the indexes where the value is 4:")
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

Find the indexes where the value is 4:
(array([3, 5, 6], dtype=int64),)


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [66]:
# The searchsorted() method is assumed to be used on sorted arrays.

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [67]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


### Numpy Array Sort

In [68]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [69]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [70]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [71]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Numpy Array Filter 

In [73]:
# Getting some elements out of an existing array and creating a new array out of them is called filtering.

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

'''
The example above will return [41, 43], why?

Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.
'''

[41 43]


'\nThe example above will return [41, 43], why?\n\nBecause the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.\n'

In [74]:
# Create a filter array that will return only values higher than 42:

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

for a in arr:
    if a>42:
        filter_arr.append(True)   
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
